### ISSUE TITLE
How is en.natural construct 

### ISSUE THREAD

**Issue by yuanliping** [ybisk/charNMT-noise#4]
The paper 'Synthetic and Natural Noise Both Break Neural Machine Translation' only introduces how to harvest naturally occurring errors for French, German, and Czech. How are the naturally occurring errors for English (listed in en.natural) constructed?

**Comment by boknilev** [comment]
I don't remember where the English natural errors are from (maybe @ybisk does?), but in any case, I don't think we ended up using them, since we only insert noise to the source-side and we always translate from another language into English.

**Comment by ybisk** [comment]
Agree that it wasn't used, but yeah, unfortunately, I'm having trouble tracking this source down.  My best guess is that it must be based on [Torsten Zesch's work](https://aclanthology.org/E12-1054/), but I'm having trouble finding an exact match.  I did find some data here but the individual instances examples line up https://github.com/zesch/spelling-experiments . He also has some work from Wikipedia edits which might be a good place to look.  Sorry!
